=== Dior-M/Dior-M.github.io/Root_folder/hw6.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Defining the root element -->
  <xs:element name="Members">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Member" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Name" type="NameType" minOccurs="1" maxOccurs="1" />
              <xs:element name="Age" type="AgeType" minOccurs="1" default="21" />
              <xs:element name="Job" type="xs:string" minOccurs="1" />
              <xs:element name="Date" type="xs:date" minOccurs="1" />
              <xs:element name="Phone" type="PhoneNumber" minOccurs="1" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- Custom NameType with maximum length -->
  <xs:simpleType name="NameType">
    <xs:restriction base="xs:string">
      <xs:maxLength value="30" />
    </xs:restriction>
  </xs:simpleType>

  <!-- Custom AgeType with minimum value and default value -->
  <xs:simpleType name="AgeType">
    <xs:restriction base="xs:positiveInteger">
      <xs:minInclusive value="21" />
      <xs:maxInclusive value="100"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Phone number pattern -->
  <xs:simpleType name="PhoneNumber">
    <xs:restriction base="xs:string">
      <xs:pattern value="\d{3}-\d{3}-\d{4}" />
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== Dior-M/Dior-M.github.io/Root_folder/hw6.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="hw6.xsl"?>

<Members xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://github.com/Dior-M/Dior-M.github.io/blob/main/Root_folder/hw6.xsd">
  <Member>
    <Name>Jonathan Mark</Name>
    <Age>22</Age>
    <Job>Consultant</Job>
    <Date>2016-05-20</Date>
    <Phone>415-343-2277</Phone>
  </Member>
  
  <!-- Testing records here -->
  
  <Member>
    <Name>Alice Johnson</Name>
    <Age>33</Age>
    <Job>Engineer</Job>
    <Date>2017-08-15</Date>
    <Phone>123-456-7890</Phone>
  </Member>
  
  <Member>
    <Name>Bob Smith</Name>
    <Age>45</Age>
    <Job>Designer</Job>
    <Date>2020-01-10</Date>
    <Phone>987-654-3210</Phone>
  </Member>
</Members>
